apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yke7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yke7
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yke7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yke7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yke7
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qrrc-tenant/rhtap-demo-app/hacbs-test-project-yke7@sha256:bc6df2bd9f70f1d65012cb792d18fb7dff104697a60b521de93f1acc337c1fb4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
