apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yke7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qrrc-tenant/rhtap-demo-app/hacbs-test-project-yke7@sha256:bc6df2bd9f70f1d65012cb792d18fb7dff104697a60b521de93f1acc337c1fb4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
